### ISSUE TITLE
请求授权：）

### ISSUE THREAD

**Issue by drinktoomuchsax** [nvssdvk/SUSTech_EE490_2023Spring#1]
学长/学姐好，能否在[SUSTech-EE-Course-Hero](https://github.com/drinktoomuchsax/SUSTech-EE-Course-Hero)里引用你的项目以及使用你的文件。会留下你的githubID以及仓库链接

**Comment by nvssdvk** [comment]
ok

**Comment by nvssdvk** [comment]
ee490是毕业设计

**Comment by drinktoomuchsax** [comment]
感谢提醒
